package:
  name: dolfyn
  version: v1.2.0

source:
  git_rev: v1.2.0
  git_url: https://github.com/lkilcher/dolfyn/.git

build:
  number: 0
  script: "python3 -m pip install . --no-deps --ignore-installed -vv"

requirements:
  build:
    - python=3.9
    - numpy>=1.21
    - scipy>=1.7.0
    - xarray>=0.19.0
    - netcdf4<1.6.0
    - bottleneck

  run:
    - python

test:
  imports:
    - dolfyn

about:
  home: https://lkilcher.github.io/dolfyn/
  license: BSD 3-Clause
  license_file: License.txt
