package:
  name: dolfyn
  version: v1.2.0

source:
  url: https://files.pythonhosted.org/packages/c2/d5/613346df7123cf2e16fbe4f13748bbd26e6840e44391b2d51fdad7fbe173/dolfyn-1.2.0.tar.gz
  sha256: c6a81557d4ff6510836a24b0d621a05b4ee35a809249d10aa3ec0c799d589c6a

requirements:
  build:
    - python=3.9
    - setuptools
    - numpy>=1.21.0
    - scipy>=1.7.0
    - xarray>=0.19.0
    - netcdf4<1.6.0
    - bottleneck

  run:
    - python
    - numpy>=1.21.0
    - scipy>=1.7.0
    - xarray>=0.19.0
    - netcdf4<1.6.0
    - bottleneck

test:
  imports:
    - dolfyn

about:
  home: https://lkilcher.github.io/dolfyn/
  license: BSD 3-Clause
  license_file: License.txt
